version: '3'

services:
  redis:
    container_name: voicereminderbot-redis
    image: redis:latest
    volumes:
      - redis_data:/data
    ports:
      - "6379:6380"
    command: redis-server --port 6380

  app:
    container_name: voicereminderbot
    build: .
    depends_on:
      - redis

volumes:
  redis_data: